services:
  - type: worker
    name: druk-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python druk.py
    envVars:
      - key: BOT_TOKEN
        sync: false